### ISSUE TITLE
[FEAT] Add: 레포지토리 초기설정

### ISSUE THREAD

**Issue by Jinlee057** [our-ml-flow/data_pipeline#1]
## Background
- 이 레포지토리는 프로젝트에 사용될 데이터 파이프라인을 구성합니다.
- 각 파이프라인은 폴더별로 관리될 예정입니다.

## Todo
- [x] 데이터라인 폴더 구조 깃헙등록
- [x] Issue template 초기 설정
- [x] Pull requests template 초기 설정

**Comment by DataHyeon** [comment]
완료자: 임성현
완료일시: 2023.08.06
