### ISSUE TITLE
[FEAT] Refactor: restructure repository

### ISSUE THREAD

**Issue by DataHyeon** [our-ml-flow/data_pipeline#10]
## Background
- 효용성을 위한 레포지터리 재구조화

## Todo
- [x] 레포지터리 폴더 재구성
   - [x] dune_nft_trades pipeline 
- [x] 폴더 재구성에 따른 관련 파일 수정
   - [x] workflow
   - [x] Dockerfile 
- [x] .gitignore 재작성
- [x] .gitignore에 포함된 기 작성된 파일 삭제
- [x] branch 세부적으로 작성하기
