### ISSUE TITLE
[FEAT] Add: alchemy_get_nfts pipeline

### ISSUE THREAD

**Issue by kangsumin2ya** [our-ml-flow/data_pipeline#12]
## Background
- Alchemy에서 get_nfts의 데이터를 일일로 가져오는 파이프라인
## Todo
- [x] 초기 폴더 구성
- [x] db에서 테이블 가져오는 task 작성
- [x] 가져온 테이블을 통해 api로 데이터 받아오는 task 작성
- [ ] 원하는 컬럼으로 테이블 만들어 db에 저장하는 task 작성
