### ISSUE TITLE
[FEAT]  Add: wash trade pipeline 

### ISSUE THREAD

**Issue by DataHyeon** [our-ml-flow/data_pipeline#19]
## Background
- ~~dune_nft_trades 테이블에서 wash trade를 확인하기 위해 추가적인 transfer 데이터 필요~~
- dune_nft_trades에서 매달 1일부터 마지막날을 기준으로 wash trade 추출 

## Todo
- [x] dune에서 transfer 테이블 확인
- [x] dune_nft_trades -> wash trade 제작 
  - [x] wash_trade를 기록하는 table 생성
    - [x] test table 생성
    - [x] insert test 확인
    - [x] python 연동 확인
    - [x] pipeline 테스트
  - [x] wash_trade의 지갑 blacklist를 기록하는 table 생성
    - [x] test table 생성
    - [x] insert test 확인
    - [x] python 연동 확인
    - [x] pipeline 테스트
  - [x]  wash_trade와 black_list을 담당하는 파이프라인 제작
