### ISSUE TITLE
[FEAT] Refactor: dune_nft_trades pipeline

### ISSUE THREAD

**Issue by kangsumin2ya** [our-ml-flow/data_pipeline#26]
## Background
- dune_nft_trades 데이터 파이프라인을 재구축합니다.

## Todo
- [x] dune ID 생성 후 API key 발급하기
- [x] 기존의 dune_nft_trades 테이블과 동일한 형태의 테이블을 만드는 파이프라인 만들기
- [ ] 원하는 형태로 테이블이 만들어진 후 인덱스 등의 설정 진행하기
