### ISSUE TITLE
[FEAT] Add: new utils function 

### ISSUE THREAD

**Issue by DataHyeon** [our-ml-flow/data_pipeline#28]
## Background
- 파이프라인의 현재 상태를 확인하는 텔레그램 기능 추가 필요성
- dune nft pipeline api 교체 기능 추가 필요성

## Todo
- [x] 파이프라인 현상태 확인 텔레그램 기능
  - [x] 기능 구현
  - [x] 멤버 추가 
- [x] dune nft pipeline api 교체 기능
- [x] 수정이 필요한 utils 함수 수정
