### ISSUE TITLE
[FEAT] Add & Update: utils, task, flow module 

### ISSUE THREAD

**Issue by DataHyeon** [our-ml-flow/data_pipeline#3]
## Background
- dune_nft_trades의 util 모듈에 새로운 함수 추가, 기존 함수 업데이트
- dune api  사용량 제한으로 인한 api 사용량 모니터링 및 교체 함수 추가 필요

## Todo
- [x] api info를 가져오는 함수 정의
- [x] api  사용량에 따른 교체 함수 정의
- [x] 다른 Task와의 연동 테스트

**Comment by DataHyeon** [comment]
담당자: 임성현
완료일시: 2023.08.06
작업내용: Close issue
